name: mysql_utils
description: This is [mysql_client] help library,This makes mysql easier to use and simple.
version: 2.0.7
homepage: https://github.com/biner88/mysql_utils
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mysql_client: ^0.0.16
