name: mysql_utils
description: This is [mysql_client] help library,This makes mysql easier to use and simple.
version: 2.1.6
homepage: https://github.com/biner88/mysql_utils
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  mysql_client_plus: #^0.0.31
    path: ../mysql_client_plus
dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.0