name: mysql_utils
description: This is [mysql_client_plus] help library,This makes mysql easier to use and simple.
version: 2.1.12
homepage: https://github.com/biner88/mysql_utils
repository: https://github.com/biner88/mysql_utils
issue_tracker: https://github.com/biner88/mysql_utils/issues
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  mysql_client_plus: ^0.1.2
dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.0