name: mysql_utils
description: This is [mysql1] help library,This makes mysql easier to use and simple. 
version: 1.0.1
homepage: https://github.com/biner88/mysql_utils
publish_to: https://pub.dev
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.19.2

dev_dependencies:
  flutter_test:
    sdk: flutter
